#!/bin/bash

# Setup script for Bare Metal micro:bit.  The tasks:
# 4. Create a file association for Geany project files.
# 5. Adjust various preferences.
# 6. Generate Geany project files for each experiment.

# Make sure the shell is bash.
if [ x$BASH_VERSION = x ]; then exec /bin/bash $0; fi

cd $(dirname $0)

/bin/echo "*** Associating project files with Geany"
/bin/mkdir -p $HOME/.local/share/applications $HOME/.local/share/mime/packages
/bin/cp application-x-geany-project.xml $HOME/.local/share/mime/packages
/bin/cp geany.desktop $HOME/.local/share/applications
update-mime-database $HOME/.local/share/mime
update-desktop-database $HOME/.local/share/applications
/bin/echo

set-option () {
    # Like crudini --set, but without the syntax error in new options
    # or troubles with trailing whitespace
    python3 houdini.py set $1 $2 $3 "$4"
}

/bin/echo "*** Making personalised settings for Geany"
mkdir -p $HOME/.config/geany/filedefs
geanyexts=$HOME/.config/geany/filetype_extensions.conf 
set-option $geanyexts Extensions GnuAS ''
set-option $geanyexts Extensions GnuARM '*.s;*.S;'
/bin/cp filetypes.GnuARM.conf $HOME/.config/geany/filedefs
/bin/echo

/bin/echo "*** Setting preferences for Geany"
geanyconf=$HOME/.config/geany/geany.conf

# Geany: Disable 'Load files from last session'
set-option $geanyconf geany pref_main_load_session false

# Geany: Enable Project Organizer
set-option $geanyconf plugins load_plugins true
plugins=$(python3 houdini.py get $geanyconf plugins active_plugins)
file=$(find /usr/lib /usr/lib64 -name projectorganizer.so -print -quit)
if [ -r $file ] && ! [[ ";$plugins" =~ ";$file;" ]]; then
    set-option $geanyconf plugins active_plugins "$plugins$file;"
fi

# Geany: Select project tab in sidebar
set-option $geanyconf geany sidebar_page 2
/bin/echo

/bin/echo "*** Installing default settings for Minicom"
/bin/cp minirc.dfl $HOME/.minirc.dfl
/bin/echo

/bin/echo "*** Generating Geany project files"
/bin/bash genproj
/bin/echo

/bin/echo "*** Done! Please log out and in again."
